# Generated by Django 5.0 on 2023-12-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customuser_delete_quickproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
