# Generated by Django 4.2.7 on 2023-12-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_quickadd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickadd',
            name='created_date',
        ),
    ]
