# Generated by Django 4.2.7 on 2023-12-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_category_quickadd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
            ],
        ),
    ]
