# Generated by Django 4.2.7 on 2023-12-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_quickadd_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickadd',
            name='kdvOrani',
            field=models.PositiveIntegerField(),
        ),
    ]
